<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Qlvb.Domain\Qlvb.Domain.csproj" />
    <ProjectReference Include="..\Qlvb.Application\Qlvb.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite.Core" />
    <PackageReference Include="SQLite3MC.PCLRaw.bundle" />
    <PackageReference Include="ClosedXML" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.Sinks.File" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Qlvb.Tests" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\*.sql" />
    <EmbeddedResource Include="Forms\*.json" />
  </ItemGroup>
</Project>
